import sys
import os

from langchain_openai import ChatOpenAI
from langchain_core.prompts import ChatPromptTemplate
from config import OPENROUTER_API_KEY, OPENROUTER_BASE_URL, MODEL_NAME
from datetime import datetime

# Connect to LLM
llm = ChatOpenAI(
    api_key=OPENROUTER_API_KEY,
    base_url=OPENROUTER_BASE_URL,
    model=MODEL_NAME
)

report_prompt = ChatPromptTemplate.from_template("""
You are a senior research director writing a professional research report.
You have been given all research findings on this topic: {topic}

SUB-QUESTIONS INVESTIGATED:
{sub_queries}

RESEARCH FINDINGS & ANALYSIS:
{summaries}

CONTRADICTION ANALYSIS:
{contradictions}

INSIGHTS & HYPOTHESES:
{insights}

Write a complete, professional research report. 
Think like you are writing for a board of directors or senior leadership team.
Be specific, cite the findings, and be actionable.

Format the report EXACTLY like this:

# RESEARCH REPORT: {topic}
**Date:** {date}
**Research Method:** Multi-Agent AI Deep Research System

---

## EXECUTIVE SUMMARY
[3-4 sentences summarizing the most important findings and what decision makers need to know]

---

## RESEARCH SCOPE
[List the 4 sub-questions that were investigated]

---

## KEY FINDINGS
[For each sub-question, write 2-3 sentences of findings with specific facts and figures]

---

## CONTRADICTIONS & UNCERTAINTIES
[What did sources disagree on? What needs more investigation?]

---

## INSIGHTS & TRENDS
[The synthesized insights and emerging trends]

---

## HYPOTHESES
[Educated predictions based on the evidence]

---

## IMPLICATIONS
### For Individuals:
[2-3 bullet points]

### For Organizations:
[2-3 bullet points]

### For Policymakers:
[2-3 bullet points]

---

## OPEN QUESTIONS FOR FURTHER RESEARCH
[2-3 questions that remain unanswered]

---

## SOURCES CONSULTED
{sources_list}

---
*Report generated by Multi-Agent AI Deep Researcher*
""")


def run_report_builder(topic: str, sub_queries: list, analysis: dict, insights: str, sources: list) -> str:
    """Takes all agent outputs, returns a complete formatted research report"""
    
    print(f"\n📝 Report Builder: Compiling final report on '{topic}'...")
    
    # Format sub queries
    sub_queries_text = ""
    for i, q in enumerate(sub_queries, 1):
        sub_queries_text += f"{i}. {q}\n"
    
    # Format summaries
    summaries_text = ""
    for s in analysis["summaries"]:
        summaries_text += f"\n### {s['query']}\n"
        summaries_text += f"{s['analysis']}\n"
        summaries_text += "---\n"
    
    # Format sources list
    sources_list = ""
    seen_urls = set()
    for s in sources:
        if s["url"] not in seen_urls:
            sources_list += f"- [{s['title']}]({s['url']})\n"
            seen_urls.add(s["url"])
    
    # Get today's date
    date = datetime.now().strftime("%B %d, %Y")
    
    # Format the prompt
    formatted_prompt = report_prompt.format_messages(
        topic=topic,
        sub_queries=sub_queries_text,
        summaries=summaries_text,
        contradictions=analysis["contradictions"],
        insights=insights,
        sources_list=sources_list,
        date=date
    )
    
    # Send to LLM
    response = llm.invoke(formatted_prompt)
    report = response.content.strip()
    
    # On Vercel filesystem is read-only so we skip saving
    filename = f"report_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md"
    print(f"✅ Report complete")
    return report, filename


# Test this agent alone
if __name__ == "__main__":
    test_topic = "Impact of artificial intelligence on jobs"
    
    test_sub_queries = [
        "What jobs are currently being replaced by AI?",
        "What new jobs is AI creating in the workforce?"
    ]
    
    test_analysis = {
        "summaries": [
            {
                "query": "What jobs are currently being replaced by AI?",
                "analysis": """SUMMARY: AI is replacing customer service, data entry, and routine cognitive jobs fastest.
CREDIBILITY: high
KEY FACT: 70% of basic customer service inquiries now handled by AI chatbots."""
            },
            {
                "query": "What new jobs is AI creating?",
                "analysis": """SUMMARY: AI trainer, prompt engineer, and AI ethicist roles are growing rapidly.
CREDIBILITY: medium
KEY FACT: LinkedIn reports 1.3 million new AI-related jobs created globally."""
            }
        ],
        "contradictions": """AGREEMENTS: AI is transforming jobs significantly
CONTRADICTIONS: Net job impact disputed between sources
UNCERTAIN CLAIMS: Exact figures need verification"""
    }
    
    test_insights = """KEY TRENDS:
- AI is shifting jobs rather than purely eliminating them
- Human oversight roles growing fastest

HYPOTHESES:
- By 2030 most displaced workers will move into AI supervision roles

IMPLICATIONS:
- Workers need AI literacy urgently
- Governments must fund retraining

OPEN QUESTIONS:
- Will net job creation stay positive as AI advances?

SURPRISING INSIGHT:
AI may be creating a human skill premium where empathy and judgment become MORE valuable."""
    
    test_sources = [
        {"title": "AI Job Displacement Report", "url": "https://example.com/1", "query": "test", "content": "", "score": 0.9},
        {"title": "LinkedIn AI Jobs Report 2024", "url": "https://example.com/2", "query": "test", "content": "", "score": 0.85}
    ]
    
    report, filename = run_report_builder(
        test_topic,
        test_sub_queries,
        test_analysis,
        test_insights,
        test_sources
    )
    
    print("\n--- REPORT PREVIEW (first 500 chars) ---")
    print(report[:500])
    print("\n... (full report saved to file)")